### ISSUE TITLE
Code Type D skipping multiple line breaks patch

### ISSUE THREAD

**Issue by jrson83** [bucanero/apollo-lib#22]
I noticed an issue with **Code Type D** on Windows 11.

When using multiple `Lines of code to skip if test fails` and inserting a `final new line` at the end of the `.savepatch` file, the patch breaks and is not applied at all.

**Update:**

The issue only occurs if `End of Line` of the file is set to `Windows (CRLF)`. If set to `Unix (LF)` the patch is applied.

This line breaks the patch when skipping **02** lines:

D8000000 **02**0130FF

Using this code:

```
[Isz Glitch Cure]
80010004 07001300 - Searches for 4 bytes of 07 00 13 00 once using Default Offset
92000000 00000DB3 - Adjusts the pointer offset by adding a value of 338 + 3169 = 3507 dec = DB3 hex to the pointer
D8000000 020130FF - Tests if 2 bytes from pointer not equal `FF 30`, skips the following two code lines if operation fails
D8000000 0103C0FF - Tests if 2 bytes from pointer equal less than `FF C0`, skips the following code line if operation fails
08000001 00000030 - Writes 1 byte with 1 offset from pointer, replacing a value less than `C0` with `30` (partial Isz glitch fix)
D8000000 0100C0FF - Tests if 2 bytes from pointer equal `FF C0`, skips the following code line if operation fails
08000001 000000FF - Writes 1 byte with 1 offset from pointer, replacing `C0` with `FF` (fully maxed out Isz glitch fix)
```

Without final newline every operation is performed successfully, in every condition:

```
D:\PS4\quick-code-test\3>patcher userdata0000.savepatch 1 userdata0000

Apollo cheat patcher v0.6.0 - (c) 2022 by Bucanero

[i] Applying codes [1] to userdata0000...

[+] Applying code #1...
- Game Genie Code
- Applying [Isz Glitch Cure] to 'userdata0000'...
- Searching (len=4 count=1) ...
- ----- Search 4 bytes -----
- 000000: 07 00 13 00                                      | ....
- ----- Search 4 bytes -----
- Search pointer = 152750 (0x254AE)
- Pointer set to offset 0x26261 (156257)
- Byte Test (00026261) C0FF != 30FF
- Byte Test (00026261) C0FF < C0FF
- Skipping 1 lines...
- Byte Test (00026261) C0FF = C0FF
- Wrote 1 bytes (FF) to 0x26262
- OK

Patching completed: 1 codes applied
```

With a final newline it does not apply the patch and outputs:

```
Apollo cheat patcher v0.6.0 - (c) 2022 by Bucanero

[i] Applying codes [1] to userdata0000...

[+] Applying code #1...
- Bruteforce Save Data Code
- Applying [Isz Glitch Cure] to 'userdata0000'...
- OK

Patching completed: 1 codes applied
```

Here you can get the savegame and patch:
[userdata0000.zip](https://github.com/bucanero/apollo-lib/files/14158615/userdata0000.zip)

**Comment by bucanero** [comment]
is your patch code actually having those comments on each line?? that's not supported and I don't even know how it worked with that stuff on the same line

if you want comments, you need to put them as
```
[my code]
; some comment line
1000ABCD 12345678
; another comment
2000FFEE DEADBEEF
80001234 4321ABCD
```

**Comment by jrson83** [comment]
@bucanero no  I'm not using any comments in the .savepatch file. Please check the attached zip file.

**Comment by jrson83** [comment]
@bucanero one update, I checked the savepatch file again. The issue only occurs if `End of Line` of the file is set to `Windows (CRLF)`. If set to `Unix (LF)` the patch is applied.

**Comment by jrson83** [comment]
Ok I see the method `get_patch_code` has a comment:

```c
 // Expects buffer without CR's (\r)
static void get_patch_code(char* buffer, int code_id, code_entry_t* entry)
```

https://github.com/bucanero/apollo-lib/blob/f717e82809cd4cc65f9bedb2761cc08d79ce071c/source/loader.c#L143

**Comment by bucanero** [comment]
I made a fix for this `CRLF` issue, I tested with your `userdata000` example and it seems to work fine, but if you can test I'll add the code to confirm it's solved

**Comment by jrson83** [comment]
> I made a fix for this `CRLF` issue, I tested with your `userdata000` example and it seems to work fine, but if you can test I'll add the code to confirm it's solved
> 

Cool, sure I will test it and reply.

**Comment by bucanero** [comment]
> > I made a fix for this `CRLF` issue, I tested with your `userdata000` example and it seems to work fine, but if you can test I'll add the code to confirm it's solved
> 
> Cool, sure I will test it and reply.

great, here's the build with the fix:
https://github.com/bucanero/apollo-lib/actions/runs/8483330873?pr=23

Just go to the bottom of the page, and download either the mingW32 or mingW64 build, depending on your Windows system (w32 or w64)

You might need to unpack the zip or tar.gz with 7zip/winrar, to get the patcher tools. Let me know your results 👍

**Comment by jrson83** [comment]
@bucanero I tested both w32 and w64 on Windows 11 Version 23H2.
I still got the same output like in version `v0.6.0`, when using `CRLF`:

```sh
# w64
D:\PS4\quick-code-test\fix>patcher userdata0000.savepatch 1 userdata0000

Apollo cheat patcher v0.7.0 - (c) 2022 by Bucanero

[i] Applying codes [1] to userdata0000...

[+] Applying code #1...
- Bruteforce Save Data Code
- Applying [Isz Glitch Cure] to 'userdata0000'...
- OK

Patching completed: 1 codes applied

# w32
D:\PS4\quick-code-test\fix32>patcher userdata0000.savepatch 1 userdata0000

Apollo cheat patcher v0.7.0 - (c) 2022 by Bucanero

[i] Applying codes [1] to userdata0000...

[+] Applying code #1...
- Bruteforce Save Data Code
- Applying [Isz Glitch Cure] to 'userdata0000'...
- OK

Patching completed: 1 codes applied
``` 

Here again I attach the patch and unpatched save file, I used for testing. The patch file is saved with vscode `CRLF` including the `final new line`.

[test-patch-apollo-crlf.zip](https://github.com/bucanero/apollo-lib/files/14817012/test-patch-apollo-crlf.zip)

**Comment by bucanero** [comment]
thanks for the feedback. I was testing on Mac and it seems that Windows had a different behavior. I'll submit another fix, This time I've tested on Windows 10 so I expect to have it solved for good.

**Comment by bucanero** [comment]
@jrson83 , can you test again with this new build? https://github.com/bucanero/apollo-lib/actions/runs/8500443080

I tested on Win10 and it's working as expected, but getting your confirmation would be great.

**Comment by jrson83** [comment]
Great, both builds are working for me on Win11 now. :+1:
